import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";
import Nav from "@/app/Components/Nav";
import Footer from "./Components/Footer";
import SubscribeToNewsLetter from "./Components/SubscribeToNewsLetter";
 
import RootLayout from "./_app";

 
const poppins = Poppins({
    display: 'swap',
    weight: ['100', '200', '300', '400', '500', '600', '700'],
    variable: '--font-poppins',
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
       <RootLayout>
            <html lang="en">
                <body
                    className={`${poppins.variable} antialiased`}
                >
                    <Nav />

                    {children}


                    <SubscribeToNewsLetter />

                    <Footer />
                </body>
            </html>
       </RootLayout>
    );
}
