import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Nav from "@/app/Components/Nav";
import Footer from "./Components/Footer";
import SubscribeToNewsLetter from "./Components/SubscribeToNewsLetter";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const poppins = Poppins({
    display: 'swap',
    weight: ['100', '200', '300', '400', '500', '600', '700'],
    variable: '--font-poppins',
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${poppins.variable} antialiased`}
            >
                <Nav />
                {children}

               <SubscribeToNewsLetter/>

                <Footer />
            </body>
        </html>
    );
}
